### ISSUE TITLE
加我好友，我是蒙面超人火騎

### ISSUE THREAD

**Issue by blankblankblankasdaasdas** [determinationlove/Baha_MasonryLayout#1]
我不知道爲什麽你在Discord block了我，但是我想跟你成爲好友，一起戰鬥
 請回應我的請求吧

**Comment by LostSoul6Years** [comment]
https://drive.google.com/file/d/10PrrpdskrJat26VdvkcMo9l7Z5FA2TxY/view?usp=sharing
